- .gitignore
- .travis.yml
- defopt.py
- setup.cfg
- setup.py
- test_defopt.py
- Try importing `sphinx.ext.napoleon` first (if you have a recent Sphinx
installed, there's no reason to have `sphinxcontrib.napoleon` installed
too).
- Try importing `unittest.mock` first in the test suite (same as above).
- Make tests runnable as `python test_defopt.py`.
- Ignore vim's `.*.swp` swap files.
> Import & test fixes.

- defopt.py
- setup.cfg
- setup.py
- test_defopt.py
See #22. Note that this PR depends on #20 (the first few commits are from that PR).
> ANSI rendering of rst markup.

- defopt.py
- test_defopt.py
This corresponds to the typical usage of single backquotes, which is to
refer to some referencable value.
I updated the tests to avoid having to put the ANSI escape codes
everywhere.
(I split out this PR as 1. the choice of highlighting perhaps less "obvious" than for bold and italic -- although I do think it is natural, and 2. it changes the tests a bit more).
> Highlight `foo` with underline.

- defopt.py
- docs/features.rst
- examples/short.py
- test_defopt.py
See #21.  Note that this PR depends on #20 (the first few commits are from that PR).
Turning off automatic generation of short flags can be achieved by replacing the `short = kwargs.pop('short', None)` line by `short = kwargs.pop('short', {})` (and updating the docs).  But I'd rather keep it on by default.
> Automatic short flags

- defopt.py
- docs/features.rst
- examples/annotations.py
- examples/starargs.py
- examples/styles.py
- test_defopt.py
The previous behavior (taking multiple callables as separate args) is
kept with a deprecation warning.  The exception thrown when no
positional argument is passed is changed to TypeError, consistently with
calling a function with arguments not matching the signature.
xref https://github.com/evanunderscore/defopt/pull/26#issuecomment-292702736
> Let `run` take a list of callables as arg.

- defopt.py
- test_defopt.py
See #28.  This works even if pathlib is not present (except that `_find_parser(None, {})` would now return None instead of raising an error, but I don't think this is a problem?).
> Add default parser for pathlib.Path.

- defopt.py
- test_defopt.py
- Display type of arguments.
- Hide default (`[]`) for varargs.
Fixes #10, #19.
> Improve help formatting.

- README.rst
- defopt.py
- docs/api.rst
- docs/features.rst
- test_defopt.py
The types and defaults are now displayed on a separate line.
This prevents the last line from getting unreasonably long
(since we're using the raw text formatter) and makes it easier
to spot type information when reading the help text.
Defaults are added for all action types except _AppendAction.
This restores the default display for boolean flags.
Examples in the documentation have been updated.
> Update display of types in help text

- defopt.py
- docs/features.rst
- test_defopt.py
> Ignore args whose name start with an underscore.

- defopt.py
All's in the title (pun intended).
Note that this makes `pydoc defopt` much cleaner.
> Define defopt.__all__.

- defopt.py
- docs/features.rst
- test_defopt.py
Note that if one of the subcommand functions has a name starting with an
underscore, an invalid parser will be generated, as the corresponding
subcommand will start with a dash and thus not be triggerable from the
command line.  However, I consider that it should be up to argparse to
raise an exception in that case -- if it doesn't do that validation, we
shouldn't bother either.
xref #44.
> Replace underscores by dashes in subcommand names.

- defopt.py
- test_defopt.py
The first commit reimplements the docstring handler to use a NodeVisitor.
The second commit adds support for bullet lists (#45).
Enumerated lists not implemented yet mostly because they're a pain as you need to handle all kinds of enumeration types (integer, alphabetic, roman) but can basically be implemented with a similar approach.
> Support bullet lists

- defopt.py
- docs/features.rst
In particular, the signature in the docstring of defopt.run *must* be on
a single line to be picked up by sphinx.
> Doc markup fixes.

- defopt.py
- test_defopt.py
Otherwise, something like
```
from typing import NamedTuple
import defopt
class T(NamedTuple):
x: str; y: str
@defopt.run
def main(p: T, q: int):
print(p)
```
crashes because `type_` changes in the closure.
Sorry I missed that.  I don't have the time to write a test right now, but can probably do so some time later, or feel free to take over the PR if you have time to.
> Fix closure over type.

- .travis.yml
- defopt.py
- setup.py
- test_defopt.py
The typing "internal" API is changing quickly, so rely on the
semi-official typing_inspect module to handle that.
Closes #57.
Failure is for Py3.3, handled by #58.
> Fix Py3.7 support.

- defopt.py
- docs/changelog.rst
- test_defopt.py
(The former was deprecated in 3.1.0, more than a year ago.)
> Remove support for passing multiple functions positionally, & dead code.

- defopt.py
- docs/changelog.rst
- test_defopt.py
Fixes part of #35.
(The hack I proposed in https://github.com/evanunderscore/defopt/issues/35#issuecomment-307604480 doesn't work at least as of Py3.7 because argparse tries to call `super(ArgumentParser, self)` which fails if ArgumentParser is patched to not be a class anymore.)
Also helps with #7 (a similar use case prompted me to write this PR): one can now use the https://docs.python.org/3/library/argparse.html#fromfile-prefix-chars feature of argparse to load the arguments from a file (perhaps it could be useful to also make https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.convert_arg_line_to_args overriddable from defopt, and that should then cover most cases, but let's not get ahead of ourselves...).
> Allow customization of ArgumentParser construction.

- defopt.py
- test_defopt.py
Previously subcommand help would not display the first line of the
docstring.  The test was incorrect because it checked whether "foo" was
in
```
usage: python -m unittest [-h] {foo,bar} ...
positional arguments:
{foo,bar}
foo
bar
optional arguments:
-h, --help  show this help message and exit
```
but of course "foo" is present, but as the command name itself.  Change
by checking for another substring.
Looks like I accidentally broke this in #47.
> Fix subcommand summary help.

- defopt.py
- docs/features.rst
- test_defopt.py
(More precisely, classes that can be constructed with a single parameter
that's moreover annotated as str.)
Implements the "implicit parser" part of https://github.com/evanunderscore/defopt/issues/69#issuecomment-508922990.
> Assume that classes with signature (...: str) are their own parsers.

- defopt.py
As suggested by https://github.com/evanunderscore/defopt/issues/69#issuecomment-508922990.
I have admittedly not looked into why this is necessary, given that I don't use Py<3.7 personally...
> Always pass evaluate=True to ti.get_args.

- defopt.py
- docs/changelog.rst
- docs/features.rst
- examples/exceptions.py
- setup.py
- test_defopt.py
See new example and documentation.
I chose to ignore the message regarding the exception in the docstring
(if any) as it would typically read less nicely (":raises FooError: if
bar" => "if bar").
I don't *actually* test that the traceback is suppressed because that
traceback is generated when the exception causes terminal unwinding of
the interpreter, so that's a bit of a pain to check unless running a
subprocess.
I bumped the napoleon dependency to 0.7 as that's needed for proper
handling of Raises block in numpydoc format (https://github.com/sphinx-contrib/napoleon/commit/beea4d12f7c9457ee7b01df28cf75543423d23cf / https://github.com/sphinx-doc/sphinx/pull/4046).
Closes (mostly) #4 (except perhaps for what to do with the exception docstring).
> Suppress traceback for exceptions listed with :raises:.

- docs/changelog.rst
> Add missing changelog entry for implicit parsers.

- defopt.py
I intentionally did not add support for subclasses of other builtin
types because I don't want to bother about whether IntEnum should be
treated as an int or an Enum...
> Support all PurePath subclasses rather than just pathlib.Path.

- defopt.py
Delete an unused variable, and make docstrings fit in one line.
> Trivial cleanups.

- .travis.yml
- defopt.py
- docs/changelog.rst
- docs/features.rst
- examples/choices.py
- setup.cfg
- setup.py
- test_defopt.py
... like enums; but easier to use for one-off scripts -- essentially maps directly to the `choices` kwarg of ArgumentParser.add_argument.
See https://docs.python.org/3.8/library/typing.html#typing.Literal.
Remove failure allowance on Py38 CI as that's how it's tested.
I chose not to make typing_extensions a dependency, but could, too.
> Add support for Literals.

- doc/source/changelog.rst
- doc/source/features.rst
- lib/defopt.py
- test_defopt.py
Thank you for very nice library.
Many command-line tools have a single flag to turn on a specified behvior and no flag to turn it off. This patch adds an optional argument `implicit_false` to `defopt.run`. If this argument is `True`, any non-positional boolean argument with `False` as a default, has no `--no-xxx` flag. This makes the command line interface simpler (user simply adds `--xxx` flat to set the value to `True` and skips it to set it to `False`).
> Add implicit_false option

- doc/source/changelog.rst
- doc/source/examples.rst
- doc/source/features.rst
- examples/nested.py
- lib/defopt.py
- test_defopt.py
Here is an initial take on using recursion for nested subcommands.  I've added tests but I have not well tested it in a "real" application yet.
The docs (help message) as briefly discussed in #89 is not implemented at this point but I do like the idea of adding a `__doc__` or similar method to add help at the "higher level" subcommands.
This implementation also requires the subcommands to be mutable mappings so that the key can be used as the subcommand name.  I'm not sure where the subcommand name would come from if nested lists were used.  Perhaps a "magic" function with `__doc__` in the name could be used for that too, if it is desired to support it.
Closes #89
> Add recursive subcommands

- .gitignore
- doc/requirements.txt
- noxfile.py
This PR comes without any previous discussion, so please feel free to just close this if it is undesired.
This adds a noxfile to automatically run the tests, coverage, and docs.  I've setup the Nox sessions to run essentially the same thing that is done in GitHub actions and the same way that read the docs should be building the docs.  Using Nox was helpful in my last PR.
If you're unfamiliar with Nox, it is similar to tox but uses a Python file to run the various sessions.  So with this, you can just run `nox` to run all tests on each Python version (use pyenv to manage them) and build the documentation locally.
https://nox.thea.codes/en/stable/index.html
I personally use pipx to install and manage nox.
> Add noxfile

- doc/source/changelog.rst
- doc/source/features.rst
- lib/defopt.py
- test_defopt.py
This is an initial implementation of the feature requested in #99.
I may not have thought through all of the potential cases here, so likely this testing would need to be expanded and the implementation thought through more closely.  But first I'd like to see if there is interest in it.
Using the code from the linked issue/feature request, it would now function as below (specifically note the line `skip = X`):
```console
$ python dummy.py
loops = 5
skip  = None
long loop iteration: 1
long loop iteration: 2
long loop iteration: 3
long loop iteration: 4
long loop iteration: 5
$ python dummy.py --skip
loops = 5
skip  = True
skipping loop printing
$ python dummy.py --no-skip
loops = 5
skip  = False
long loop iteration: 1
long loop iteration: 2
long loop iteration: 3
long loop iteration: 4 …
```
> Make Optional[bool] still act as a flag

- lib/defopt.py
- test_defopt.py
Before:
```
ValueError: no type found for parameter s
```
After:
```
Exception: no parser found for type NotConstructibleFromStr
```
> Fix exception for unparseable types

- lib/defopt.py
- test_defopt.py
> Add support for Optional[Tuple[...]] (#115)
